working_directory = "workspace/"
image_directory = "reduced_images/"
fits_extension = ".fit"
reduced_prefix = "r_"
catalogue_prefix = "catalogue_"
standard_file_extension = ".txt"
table_format = "ascii"
time_file = "times" + standard_file_extension
shift_file = "shifts" + standard_file_extension
catalogue_shift_file = "catalogue_" + shift_file
flux_directory = "fluxes/"
light_curve_directory = "light_curves/"
flux_prefix = "fluxes_"
identifier = "id"
id_map_file = "id_mapping" + standard_file_extension
adjusted_curves_directory = "adjusted_light_curves/"
output_directory = "results/"
variability_threshold = 0.8
folder = "C:/Users/benwa/Documents/Semester 2 Project 2/0131x/"
file_name = "l197.5"
has_sets = True
set_size = 50
n_sets = 9
check_radius = 10
cosmic_threshold = 5
flux_cutoff = 100
edge_limit = 50
inner_radius = 8
outer_radius = 13
api_key = "tbdnkqfbeefqjvzw"
job_file_name = "astrometryjob.txt"
image_width = 2432
image_height = 1600
moving_obj_check_image = 30
moving_obj_folder = "moving_objects/"
moving_obj_file = "moving_objects.txt"
streak_folder = "streaks/"
streak_file = "streaks.txt"


